// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_8oQTh_nlpp9wil1IYxJHjVwkUvD_8nw',
    appId: '1:424166767516:web:4994f8813db6ecb9f16659',
    messagingSenderId: '424166767516',
    projectId: 'login-regis--firebase',
    authDomain: 'login-regis--firebase.firebaseapp.com',
    storageBucket: 'login-regis--firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrPopJIMwgSUUJPIOTUdlG6YaXdeOoRzI',
    appId: '1:424166767516:android:46582e19831f73f2f16659',
    messagingSenderId: '424166767516',
    projectId: 'login-regis--firebase',
    storageBucket: 'login-regis--firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwyHO3fWhL73BvUP4hzbcRMbfBJFrv8Ho',
    appId: '1:424166767516:ios:6e1d7513b01bd080f16659',
    messagingSenderId: '424166767516',
    projectId: 'login-regis--firebase',
    storageBucket: 'login-regis--firebase.appspot.com',
    iosClientId:
        '424166767516-0juv9593etnrtqgmp3cqmltvkg35d93s.apps.googleusercontent.com',
    iosBundleId: 'com.example.virta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwyHO3fWhL73BvUP4hzbcRMbfBJFrv8Ho',
    appId: '1:424166767516:ios:6e1d7513b01bd080f16659',
    messagingSenderId: '424166767516',
    projectId: 'login-regis--firebase',
    storageBucket: 'login-regis--firebase.appspot.com',
    iosClientId:
        '424166767516-0juv9593etnrtqgmp3cqmltvkg35d93s.apps.googleusercontent.com',
    iosBundleId: 'com.example.virta',
  );
}
